# -*- coding: utf-8 -*-
"""gitgub_test_streamlit_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nCrfbuGbA4-917LlccUqiiLIXaup7JzE
"""

from google.colab import drive
drive.mount('/content/drive/')

!pip install -q streamlit

import streamlit as st
import pandas as pd

"""
# My first app
Here's our first attempt at using data to create a table:
"""

df = pd.DataFrame({
  'first column': [1, 2, 3, 4],
  'second column': [10, 20, 30, 40]
})

df

