# -*- coding: utf-8 -*-
"""streamlit_test_v4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12cqeLMQxkWLH6Cl5P6pQ-UrMd9a6ki2k
"""

# Draw a title and some text to the app:
'''
# This is the document title

This is some _markdown_.
'''
#import streamlit as st

import pandas as pd
df = pd.DataFrame({'col1': [1,2,3]})
df  # 👈 Draw the dataframe

x = 10
'x', x  # 👈 Draw the string 'x' and then the value of x

# Also works with most supported chart types
import matplotlib.pyplot as plt
import numpy as np

arr = np.random.normal(1, 1, size=100)
fig, ax = plt.subplots()
ax.hist(arr, bins=20)

fig  # 👈 Draw a Matplotlib chart
st.pyplot(fig)

